dist: xenial
sudo: yes

addons:
    chrome: stable
    apt:
        packages:
            - chromium-chromedriver
before_script:
    - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
    - pip install selenium
 
language: python
python:
    - '3.7'
 
 
 script:
    - python test_parser.py
